[package]
name = "libsui"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "A injection tool for executable formats (ELF, PE, Mach-O) that allows you to embed files into existing binary and extract them at runtime"
homepage = "https://sui.littledivy.com"
repository = "https://github.com/littledivy/sui"

[dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = ["Win32_System", "Win32_System_LibraryLoader", "Win32_Foundation"] }

[target.'cfg(not(windows))'.build-dependencies]
cmake = "0.1"
