name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      SUI_FROM_SOURCE: true

    steps:
    - uses: actions/checkout@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      if: matrix.os == 'windows-latest'
    - name: Build
      run: cargo b -vv
    - name: Build cli
      run: |
        cd cli
        cargo b -vv
